apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets
spec:
  selector:
    matchLabels:
      app: vets
  replicas: 2
  template:
    metadata:
      labels:
        app: vets
    spec:
      containers:
        - name: vets
          image: spring2go/spring-petclinic-vets-service:1.0.0.RELEASE
          envFrom:
            - configMapRef:
                name: petclinic-config
---
apiVersion: v1
kind: Service
metadata:
  name: vets
spec:
  selector:
    app: vets
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
