apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits
spec:
  selector:
    matchLabels:
      app: visits
  replicas: 2
  template:
    metadata:
      labels:
        app: visits
    spec:
      containers:
        - name: visits
          image: spring2go/spring-petclinic-visits-service:1.0.0.RELEASE
          envFrom:
            - configMapRef:
                name: petclinic-config
---
apiVersion: v1
kind: Service
metadata:
  name: visits
spec:
  selector:
    app: visits
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
