apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits
spec:
  selector:
    matchLabels:
      app: visits
  replicas: 1
  template:
    metadata:
      labels:
        app: visits
    spec:
      containers:
        - name: visits
          image: spring2go/spring-petclinic-visits-service:1.0.0.RELEASE
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "512Mi"
          env:
            - name: JAVA_OPTS
              value: "-XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -XX:+HeapDumpOnOutOfMemoryError"
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: visits
spec:
  selector:
    app: visits
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
