spring:
  application:
    name: web-app

server:
  port: 8081

# Logging
logging.level.org.springframework: INFO

# Internationalization
spring.messages.basename: messages/messages

# Metrics
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

petclinic:
  visits-service-endpoint: ${VISITS_SERVICE_ENDPOINT:http://localhost:8083}
  customers-service-endpoint: ${CUSTOMERS_SERVICE_ENDPOINT:http://localhost:8084}